CREATE TABLE IF NOT EXISTS `bank_statement_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`date` text NOT NULL,
	`description` text NOT NULL,
	`time` text,
	`phonepe_name` text,
	`ref_no` text,
	`debit` real,
	`credit` real,
	`balance` real,
	`account_number` text,
	`bank_name` text,
	`expense_name` text,
	`expense_type` text,
	`category_id` integer,
	`account_id` integer,
	`from_account_id` integer,
	`to_account_id` integer,
	`note` text,
	`tags` text,
	`is_classified` integer DEFAULT false NOT NULL,
	`is_dismissed` integer DEFAULT false NOT NULL,
	`expense_transaction_id` integer,
	`created_at` text NOT NULL,
	FOREIGN KEY (`category_id`) REFERENCES `expense_accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`account_id`) REFERENCES `expense_accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`from_account_id`) REFERENCES `expense_accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`to_account_id`) REFERENCES `expense_accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`expense_transaction_id`) REFERENCES `expense_transactions`(`id`) ON UPDATE no action ON DELETE no action
);
